yolo_model:

  config_file:
    name: blockade_sign.cfg
  weight_file:
    name: blockade_sign.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - blockade_sign

image_view:

    enable_opencv: false
