yolo_model:

  config_file:
    name: traffic_light.cfg
  weight_file:
    name: traffic_light.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - traffic_light_black
      - traffic_light_red
      - traffic_light_blue

image_view:

    enable_opencv: false
